language: node_js
cache:
  directories:
  - node_modules
node_js:
- '6'
before_script:
- npm prune
script:
- npm t
notifications:
  slack:
    rooms:
      - secure: "sdfusdhfsdofguhdfgubdsifgudfbgs3453durghssecurestringidsuag34522irueg="
    on_success: always